from .BaseAgent import BaseAgent
from .VanillaDQN import VanillaDQN
from .DQN import DQN
from .DDQN import DDQN
from .MaxminDQN import MaxminDQN
from .EnsembleDQN import EnsembleDQN
from .AveragedDQN import AveragedDQN

from .REINFORCE import REINFORCE
from .ActorCritic import ActorCritic
from .PPO import PPO
from .SAC import SAC
from .DDPG import DDPG
from .TD3 import TD3
from .RepOffPG import RepOffPG
from .RepOnPG import RepOnPG
from .OffRPG import OffRPG
from .OnRPG import OnRPG
from .OnRPG2 import OnRPG2
from .OnRPG3 import OnRPG3
from .OnRPG4 import OnRPG4
from .OnRPG5 import OnRPG5
from .OnRPG6 import OnRPG6