from .BaseAgent import BaseAgent
from .VanillaDQN import VanillaDQN
from .DQN import DQN
from .DDQN import DDQN
from .MaxminDQN import MaxminDQN
from .EnsembleDQN import EnsembleDQN
from .AveragedDQN import AveragedDQN

from .REINFORCE import REINFORCE
from .ActorCritic import ActorCritic
from .PPO import PPO
from .PPO2 import PPO2
from .SAC import SAC
from .DDPG import DDPG
from .TD3 import TD3
from .RepOffPG import RepOffPG
from .RepOnPG import RepOnPG
from .OffRPG import OffRPG
from .OffRPG2 import OffRPG2
from .OnRPG import OnRPG
from .OnRPG1 import OnRPG1
from .OnRPG2 import OnRPG2